version: '3'

services:
	mariadb:
		image: mariadb
		container_name: mariadb
		volumes:
			- mariadb:/var/lib/mysql
		networks:
			- inception
		build:
			context: requirements/mariadb
			dockerfile: Dockerfile
		env_file: .env
		restart: on-failure
		expose:
			- "3306"